[package]
name = "case-converter"
version = "0.1.0"
edition = "2021"
description = "A CLI tool to convert text between different cases"

[dependencies]
clap = { version = "4.4", features = ["derive"] }